name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download libtorch
      run: |
        rm -rf libtorch.zip libtorch/
        ./scripts/download_libtorch.sh
        unzip libtorch.zip
    - name: Build
      env:
        LIBTORCH: "${{ github.workspace }}/libtorch"
        LIBTORCH_INCLUDE: "${{ github.workspace }}/libtorch/include"
      run: env && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
